name: BUILD WORKFLOW
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:    
      workdir: ./backend
    strategy:
      matrix:
        node-version: [18,16]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        # context: './backend/'
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: "**/pnpm-lock.yaml"
    - name: Install dependencies
      run: pnpm install
      working-directory: ${{env.workdir}}
    - name: Build
      run: pnpm run build
      working-directory: ./backend
    # - run: pnpm install
    # - run: pnpm run build